### ISSUE TITLE
код не является exception-safe там, где это жизненно необходимо

### ISSUE THREAD

**Issue by NewYaroslav** [NewYaroslav/easy_plot_cpp#3]
Перед изменением drawings соответствующий mutex lock'чится, после изменения — раз'lock'чивается назад. Между этими двумя моментами вызываются функции push_back и make_shared, каждая из которых может выбросить исключение. Библиотечный код при этом не раз'lock'чит mutex, и при попытке повторно его за'lock'чить всё повиснет.

**Comment by LimiNode** [comment]
Исправлено
